/**
 * V1-01 to V1-03, V1-14: the asset set under src/assets/, its manifest
 * (src/assets/assets.json) and the token colours a served SVG may use.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { SvgKind } from "./svg-check";

export const ASSET_DIR = "src/assets";
export const MANIFEST = `${ASSET_DIR}/assets.json`;
export const LICENCE = "Original work for Belvoir Finance, all rights reserved";
export const AUTHOR = "Forge (bot)";

export interface ManifestEntry {
  path: string;
  kind: "illustration" | "icon" | "pattern" | "diagram";
  /** Byte-cap kind (V1-11). */
  cap: SvgKind;
  /** Rule 5 id prefix. */
  idPrefix: string;
  author: string;
  method: string;
  licence: string;
  sha256: string;
}

/** Every hex colour declared in tokens.css (lower-case, 6 digits). */
export function tokenHexValues(tokensCss = readFileSync("src/styles/tokens.css", "utf8")): Set<string> {
  return new Set(
    [...tokensCss.matchAll(/--color-[\w-]+:\s*(#[0-9a-fA-F]{6})\b/g)].map((m) => (m[1] ?? "").toLowerCase()),
  );
}

export function sha256(file: string): string {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

/** Every file under a directory, as repo-relative paths. */
export function filesUnder(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const n of readdirSync(dir)) {
    const p = join(dir, n);
    if (statSync(p).isDirectory()) out.push(...filesUnder(p));
    else out.push(relative(".", p).replace(/\\/g, "/"));
  }
  return out.sort();
}

export function readManifest(file = MANIFEST): ManifestEntry[] {
  return (JSON.parse(readFileSync(file, "utf8")) as { assets: ManifestEntry[] }).assets;
}

/**
 * V1-02: problems with a manifest against the files in a directory: a file not
 * listed, a row with no file, a wrong hash or a missing provenance field.
 */
export function manifestProblems(entries: readonly ManifestEntry[], dir = ASSET_DIR): string[] {
  const problems: string[] = [];
  const files = filesUnder(dir).filter((f) => !f.endsWith("/assets.json") && !f.endsWith("/ASSETS.md"));
  const listed = new Set(entries.map((e) => e.path));
  for (const f of files) if (!listed.has(f)) problems.push(`${f}: not in the manifest`);
  for (const e of entries) {
    if (!existsSync(e.path)) {
      problems.push(`${e.path}: manifest row has no file`);
      continue;
    }
    if (sha256(e.path) !== e.sha256) problems.push(`${e.path}: sha256 differs from the manifest`);
    if (e.licence !== LICENCE) problems.push(`${e.path}: licence must be "${LICENCE}"`);
    if (e.author !== AUTHOR) problems.push(`${e.path}: author must be "${AUTHOR}"`);
    if (!/^(hand-authored SVG|generated by scripts\/[\w./-]+)$/.test(e.method))
      problems.push(`${e.path}: method must be "hand-authored SVG" or "generated by scripts/<file>"`);
    if (!["illustration", "icon", "pattern", "diagram"].includes(e.kind)) problems.push(`${e.path}: unknown kind`);
  }
  return problems;
}
